name: task_buddy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  velocity_x: ^4.1.2
  flutter_bloc: ^8.1.4
  auto_route: ^7.8.4
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_asset_generator: ^1.1.0
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  provider: ^6.1.1
  lottie: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_datetime_picker_plus: ^2.1.0
  bloc: ^8.1.3
  meta: ^1.10.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  talker_bloc_logger: ^4.0.3
  http: ^1.2.0
  talker: ^4.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/illustrations/
